# Generated by Django 4.1 on 2022-09-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cretead_by',
            new_name='created_by',
        ),
    ]
