# Generated by Django 4.1 on 2022-09-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_posts', '0002_rename_cretead_by_post_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
