# Generated by Django 4.1 on 2022-10-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_posts', '0004_alter_post_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/image'),
        ),
    ]
